//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIDV.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bidv__card
    {
        public bidv__card()
        {
            this.bidv__promotion_card = new HashSet<bidv__promotion_card>();
            this.bidv__slogan = new HashSet<bidv__slogan>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string title_seo { get; set; }
        public Nullable<int> weight { get; set; }
        public Nullable<short> status { get; set; }
        public Nullable<int> created { get; set; }
        public string lang { get; set; }
        public Nullable<int> pid { get; set; }
        public Nullable<int> type_id { get; set; }
        public string image { get; set; }
        public string hanmuc { get; set; }
        public string slogan { get; set; }
        public string bieuphi { get; set; }
        public string title_text { get; set; }
    
        public virtual bidv__category bidv__category { get; set; }
        public virtual ICollection<bidv__promotion_card> bidv__promotion_card { get; set; }
        public virtual ICollection<bidv__slogan> bidv__slogan { get; set; }
    }
}
