//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIDV.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bidv__streets
    {
        public int id { get; set; }
        public Nullable<int> city_id { get; set; }
        public string title { get; set; }
        public short status { get; set; }
        public string md5_title { get; set; }
        public int district_id { get; set; }
    
        public virtual bidv__districts bidv__districts { get; set; }
    }
}
