//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIDV.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bidv__tag_items
    {
        public int id { get; set; }
        public Nullable<int> tag_id { get; set; }
        public int item_id { get; set; }
        public Nullable<short> type { get; set; }
    
        public virtual bidv__news bidv__news { get; set; }
        public virtual bidv__tags bidv__tags { get; set; }
    }
}
