//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIDV.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bidv__attach_detail
    {
        public int id { get; set; }
        public Nullable<int> object_id { get; set; }
        public string object_type { get; set; }
        public Nullable<int> attach_id { get; set; }
        public Nullable<int> created { get; set; }
    
        public virtual bidv__attach bidv__attach { get; set; }
    }
}
