//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIDV.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bidv___roles
    {
        public bidv___roles()
        {
            this.bidv___users = new HashSet<bidv___users>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string permit { get; set; }
        public short rank { get; set; }
        public Nullable<int> created { get; set; }
    
        public virtual ICollection<bidv___users> bidv___users { get; set; }
    }
}
