//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIDV.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bidv___province
    {
        public bidv___province()
        {
            this.bidv__promotion_city = new HashSet<bidv__promotion_city>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public short position { get; set; }
        public string status { get; set; }
        public string yahoo { get; set; }
        public string hotline { get; set; }
        public string fax { get; set; }
        public string skype { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public string name_facebook { get; set; }
        public string safe_title { get; set; }
        public Nullable<short> is_city { get; set; }
    
        public virtual ICollection<bidv__promotion_city> bidv__promotion_city { get; set; }
    }
}
