//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIDV.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bidv___lang
    {
        public int id { get; set; }
        public int pid { get; set; }
        public string title { get; set; }
        public short is_main { get; set; }
        public string lang { get; set; }
        public int created { get; set; }
        public string page_used { get; set; }
        public short type { get; set; }
    }
}
