//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIDV.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bidv___file_upload
    {
        public int id { get; set; }
        public string file { get; set; }
        public string type { get; set; }
        public Nullable<int> size { get; set; }
        public Nullable<int> time { get; set; }
        public Nullable<int> created { get; set; }
    }
}
