//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIDV.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bidv__category
    {
        public bidv__category()
        {
            this.bidv__card = new HashSet<bidv__card>();
            this.bidv__news = new HashSet<bidv__news>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string safe_title { get; set; }
        public Nullable<int> parent_id { get; set; }
        public string image { get; set; }
        public Nullable<int> weight { get; set; }
        public string icon { get; set; }
        public Nullable<short> active { get; set; }
        public Nullable<int> created { get; set; }
        public Nullable<short> status { get; set; }
        public Nullable<short> type { get; set; }
        public string mota { get; set; }
        public string tinh_nang { get; set; }
        public string diem_gd { get; set; }
        public string sosanh { get; set; }
        public string nut { get; set; }
        public string color { get; set; }
        public bool isPromotion { get; set; }
    
        public virtual ICollection<bidv__card> bidv__card { get; set; }
        public virtual ICollection<bidv__news> bidv__news { get; set; }
    }
}
