//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIDV.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bidv__system
    {
        public int id { get; set; }
        public string domain_name { get; set; }
        public string keywords { get; set; }
        public string description { get; set; }
        public string email { get; set; }
        public string email_order { get; set; }
        public string email_marketing { get; set; }
        public string link_facebook { get; set; }
        public string link_youtube { get; set; }
        public string link_in { get; set; }
        public string address { get; set; }
        public string logo_title { get; set; }
        public string logo { get; set; }
        public string favicon { get; set; }
        public string background { get; set; }
        public int website_status { get; set; }
        public string currency { get; set; }
        public string site_name { get; set; }
        public string googlemap { get; set; }
    }
}
