//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIDV.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bidv__menu
    {
        public int id { get; set; }
        public string title { get; set; }
        public string link { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<int> weight { get; set; }
        public Nullable<bool> no_follow { get; set; }
        public Nullable<bool> target { get; set; }
        public int position { get; set; }
        public Nullable<int> parent { get; set; }
    }
}
