//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIDV.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bidv___page
    {
        public bidv___page()
        {
            this.bidv___block = new HashSet<bidv___block>();
        }
    
        public int id { get; set; }
        public string layout_mobile { get; set; }
        public string layout { get; set; }
        public string name { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string rewrite { get; set; }
        public string themes_mobile { get; set; }
        public string themes { get; set; }
    
        public virtual ICollection<bidv___block> bidv___block { get; set; }
    }
}
