//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIDV.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bidv___user_block
    {
        public int id { get; set; }
        public int block_day { get; set; }
        public int block_user { get; set; }
        public string block_reason { get; set; }
        public int uid { get; set; }
        public int created { get; set; }
        public short type { get; set; }
    
        public virtual bidv___users bidv___users { get; set; }
    }
}
