//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIDV.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bidv__faqs
    {
        public int id { get; set; }
        public string question { get; set; }
        public string answer { get; set; }
        public Nullable<int> created { get; set; }
        public Nullable<short> status { get; set; }
        public string lang { get; set; }
        public Nullable<int> cat_id { get; set; }
    }
}
