//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIDV.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bidv__tags
    {
        public bidv__tags()
        {
            this.bidv__tag_items = new HashSet<bidv__tag_items>();
        }
    
        public int id { get; set; }
        public string tag { get; set; }
        public string title { get; set; }
        public Nullable<short> type { get; set; }
        public Nullable<int> created { get; set; }
        public Nullable<short> status { get; set; }
        public string images { get; set; }
        public Nullable<short> is_hot { get; set; }
    
        public virtual ICollection<bidv__tag_items> bidv__tag_items { get; set; }
    }
}
