//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIDV.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bidv__feature
    {
        public int id { get; set; }
        public string title { get; set; }
        public string link { get; set; }
        public string image { get; set; }
        public Nullable<int> weight { get; set; }
        public Nullable<short> status { get; set; }
        public Nullable<short> show { get; set; }
        public string url_show { get; set; }
        public Nullable<int> created { get; set; }
        public string body { get; set; }
        public short type { get; set; }
        public string lang { get; set; }
        public Nullable<int> pid { get; set; }
        public Nullable<int> start { get; set; }
        public Nullable<int> end { get; set; }
        public string nut { get; set; }
    }
}
