//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIDV.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bidv___logs
    {
        public int id { get; set; }
        public Nullable<int> uid { get; set; }
        public string uname { get; set; }
        public Nullable<int> object_id { get; set; }
        public Nullable<int> fucked_id { get; set; }
        public string type { get; set; }
        public string action { get; set; }
        public string note { get; set; }
        public Nullable<int> time { get; set; }
        public string ip { get; set; }
    
        public virtual bidv___users bidv___users { get; set; }
    }
}
