//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIDV.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bidv__promotion
    {
        public bidv__promotion()
        {
            this.bidv__promotion_card = new HashSet<bidv__promotion_card>();
            this.bidv__promotion_city = new HashSet<bidv__promotion_city>();
            this.bidv__promotion_des = new HashSet<bidv__promotion_des>();
            this.bidv__promotion_img = new HashSet<bidv__promotion_img>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string title_seo { get; set; }
        public Nullable<int> weight { get; set; }
        public Nullable<short> status { get; set; }
        public int created { get; set; }
        public string lang { get; set; }
        public Nullable<int> pid { get; set; }
        public Nullable<int> time_from { get; set; }
        public Nullable<int> time_to { get; set; }
        public Nullable<int> view { get; set; }
        public Nullable<int> promo_per { get; set; }
        public string company { get; set; }
        public string website { get; set; }
        public int cat_id { get; set; }
        public short is_hot { get; set; }
        public short is_home { get; set; }
        public string image_ngang { get; set; }
        public string image_doc { get; set; }
    
        public virtual ICollection<bidv__promotion_card> bidv__promotion_card { get; set; }
        public virtual ICollection<bidv__promotion_city> bidv__promotion_city { get; set; }
        public virtual ICollection<bidv__promotion_des> bidv__promotion_des { get; set; }
        public virtual ICollection<bidv__promotion_img> bidv__promotion_img { get; set; }
    }
}
