//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIDV.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bidv__attach
    {
        public bidv__attach()
        {
            this.bidv__attach_detail = new HashSet<bidv__attach_detail>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string ext { get; set; }
        public string type { get; set; }
        public Nullable<int> size { get; set; }
        public Nullable<int> created { get; set; }
        public Nullable<short> status { get; set; }
    
        public virtual ICollection<bidv__attach_detail> bidv__attach_detail { get; set; }
    }
}
