//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIDV.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bidv__news
    {
        public bidv__news()
        {
            this.bidv__news_image = new HashSet<bidv__news_image>();
            this.bidv__tag_items = new HashSet<bidv__tag_items>();
        }
    
        public int id { get; set; }
        public Nullable<int> cat_id { get; set; }
        public string title { get; set; }
        public string title_seo { get; set; }
        public string sort_body { get; set; }
        public string body { get; set; }
        public short status { get; set; }
        public int created { get; set; }
        public int changed { get; set; }
        public int uid { get; set; }
        public string user_name { get; set; }
        public Nullable<int> sort { get; set; }
        public string lang { get; set; }
        public Nullable<int> view { get; set; }
        public Nullable<short> type { get; set; }
        public Nullable<int> dateof { get; set; }
        public Nullable<short> is_hot { get; set; }
        public short is_home { get; set; }
        public Nullable<int> time_from { get; set; }
        public Nullable<int> time_to { get; set; }
    
        public virtual bidv__category bidv__category { get; set; }
        public virtual ICollection<bidv__news_image> bidv__news_image { get; set; }
        public virtual ICollection<bidv__tag_items> bidv__tag_items { get; set; }
    }
}
