//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIDV.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bidv__promotion_img
    {
        public int id { get; set; }
        public string image { get; set; }
        public Nullable<int> promo_id { get; set; }
        public Nullable<int> weight { get; set; }
        public Nullable<int> created { get; set; }
        public Nullable<short> type { get; set; }
    
        public virtual bidv__promotion bidv__promotion { get; set; }
    }
}
