//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIDV.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BIDVEntities : DbContext
    {
        public BIDVEntities()
            : base("name=BIDVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bidv___block> bidv___block { get; set; }
        public virtual DbSet<bidv___configs> bidv___configs { get; set; }
        public virtual DbSet<bidv___file_upload> bidv___file_upload { get; set; }
        public virtual DbSet<bidv___lang> bidv___lang { get; set; }
        public virtual DbSet<bidv___logs> bidv___logs { get; set; }
        public virtual DbSet<bidv___module> bidv___module { get; set; }
        public virtual DbSet<bidv___page> bidv___page { get; set; }
        public virtual DbSet<bidv___province> bidv___province { get; set; }
        public virtual DbSet<bidv___roles> bidv___roles { get; set; }
        public virtual DbSet<bidv___user_block> bidv___user_block { get; set; }
        public virtual DbSet<bidv___users> bidv___users { get; set; }
        public virtual DbSet<bidv__attach> bidv__attach { get; set; }
        public virtual DbSet<bidv__attach_detail> bidv__attach_detail { get; set; }
        public virtual DbSet<bidv__card> bidv__card { get; set; }
        public virtual DbSet<bidv__category> bidv__category { get; set; }
        public virtual DbSet<bidv__districts> bidv__districts { get; set; }
        public virtual DbSet<bidv__faqs> bidv__faqs { get; set; }
        public virtual DbSet<bidv__feature> bidv__feature { get; set; }
        public virtual DbSet<bidv__gallery> bidv__gallery { get; set; }
        public virtual DbSet<bidv__gallery_cats> bidv__gallery_cats { get; set; }
        public virtual DbSet<bidv__news> bidv__news { get; set; }
        public virtual DbSet<bidv__news_image> bidv__news_image { get; set; }
        public virtual DbSet<bidv__promotion> bidv__promotion { get; set; }
        public virtual DbSet<bidv__promotion_card> bidv__promotion_card { get; set; }
        public virtual DbSet<bidv__promotion_city> bidv__promotion_city { get; set; }
        public virtual DbSet<bidv__promotion_des> bidv__promotion_des { get; set; }
        public virtual DbSet<bidv__promotion_img> bidv__promotion_img { get; set; }
        public virtual DbSet<bidv__streets> bidv__streets { get; set; }
        public virtual DbSet<bidv__subscribe> bidv__subscribe { get; set; }
        public virtual DbSet<bidv__tag_items> bidv__tag_items { get; set; }
        public virtual DbSet<bidv__tags> bidv__tags { get; set; }
        public virtual DbSet<aspnet_Users> aspnet_Users { get; set; }
        public virtual DbSet<bidv__slogan> bidv__slogan { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
        public virtual DbSet<webpages_Membership> webpages_Membership { get; set; }
        public virtual DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public virtual DbSet<webpages_Roles> webpages_Roles { get; set; }
        public virtual DbSet<webpages_UsersInRoles> webpages_UsersInRoles { get; set; }
        public virtual DbSet<view_UserProfile> view_UserProfile { get; set; }
        public virtual DbSet<view_UserRoles> view_UserRoles { get; set; }
        public virtual DbSet<bidv__menu> bidv__menu { get; set; }
        public virtual DbSet<bidv__system> bidv__system { get; set; }
    }
}
